version: "3"

services:
  backend:
    build:
      context: ./golang
    ports:
      - "8081:8080"
    tty: true
    stdin_open: true
    # command: go run main.go
    volumes:
      - ./golang:/go/src
    environment:
      MYSQL_DATABASE: mygraphql
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mygraphql
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_USER: usr
      # MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
volumes:
  mysql_data:
